# Generated by Django 2.2 on 2019-05-21 10:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaApp', '0004_auto_20190430_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='url_info',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_info',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='SongRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediaApp.Song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediaApp.UserProfileInfo')),
            ],
        ),
    ]
