# Generated by Django 2.2 on 2019-05-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaApp', '0004_auto_20190430_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='url_info',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='url_info',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='songcomment',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
