# Generated by Django 2.2 on 2019-05-24 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MediaApp', '0005_auto_20190524_0902'),
        ('MediaApp', '0005_auto_20190521_1050'),
    ]

    operations = [
    ]
