# Generated by Django 2.2 on 2019-05-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaApp', '0006_merge_20190524_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songcomment',
            name='content',
            field=models.CharField(max_length=500),
        ),
    ]
