FROM python:3.6-alpine
RUN apk update

RUN mkdir /app
ADD requirements.txt /app
WORKDIR /app

RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install -r requirements.txt --no-cache-dir && \
 apk --purge del .build-deps
ADD . /app/
