# Generated by Django 2.1.7 on 2019-04-09 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MediaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url_info', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=200)),
                ('release_date', models.DateField(default=datetime.date.today)),
                ('genre', models.CharField(max_length=50)),
                ('url_info', models.URLField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MediaApp.Group')),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='movie',
            name='url_info',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='bday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
